import type { EnemyDefinition } from '@/types/adventure'
import { GENERATED_ENEMIES } from './generatedEnemies'

export const ENEMIES: Record<string, EnemyDefinition> = {
  ...GENERATED_ENEMIES,
  slime: {
    id: 'slime',
    name: '史莱姆',
    icon: '🟢',
    realm: '炼气',
    realmLevel: 1,
    baseStats: { maxHp: 50, attack: 8, defense: 3, speed: 80 },
    skills: ['tackle'],
    drops: ['herb_grass'],
    expReward: 5,
    goldReward: { min: 2, max: 5 }
  },
  wild_wolf: {
    id: 'wild_wolf',
    name: '野狼',
    icon: '🐺',
    realm: '炼气',
    realmLevel: 2,
    baseStats: { maxHp: 80, attack: 15, defense: 5, speed: 110 },
    skills: ['bite', 'swift_strike'],
    drops: ['wolf_fang'],
    expReward: 8,
    goldReward: { min: 3, max: 8 }
  },
  forest_spider: {
    id: 'forest_spider',
    name: '林中蛛',
    icon: '🕷️',
    realm: '炼气',
    realmLevel: 3,
    baseStats: { maxHp: 60, attack: 12, defense: 4, speed: 95 },
    skills: ['poison_bite', 'web'],
    drops: ['spider_silk'],
    expReward: 10,
    goldReward: { min: 5, max: 10 }
  },
  cave_bat: {
    id: 'cave_bat',
    name: '洞穴蝙蝠',
    icon: '🦇',
    realm: '炼气',
    realmLevel: 4,
    baseStats: { maxHp: 70, attack: 14, defense: 4, speed: 130 },
    skills: ['sonic_wave', 'drain'],
    drops: ['bat_wing'],
    expReward: 12,
    goldReward: { min: 5, max: 12 }
  },
  rock_golem: {
    id: 'rock_golem',
    name: '岩石魔像',
    icon: '🗿',
    realm: '炼气',
    realmLevel: 5,
    baseStats: { maxHp: 200, attack: 20, defense: 25, speed: 60 },
    skills: ['rock_throw', 'earth_shield'],
    drops: ['iron_ore', 'golem_core'],
    expReward: 20,
    goldReward: { min: 10, max: 20 }
  },
  shadow_snake: {
    id: 'shadow_snake',
    name: '暗影蛇',
    icon: '🐍',
    realm: '炼气',
    realmLevel: 6,
    baseStats: { maxHp: 90, attack: 25, defense: 6, speed: 120 },
    skills: ['shadow_strike', 'venom'],
    drops: ['shadow_essence'],
    expReward: 18,
    goldReward: { min: 8, max: 18 }
  },
  sand_worm: {
    id: 'sand_worm',
    name: '沙虫',
    icon: '🐛',
    realm: '筑基',
    realmLevel: 2,
    baseStats: { maxHp: 120, attack: 22, defense: 8, speed: 85 },
    skills: ['sand_blast', 'burrow'],
    drops: ['sand_crystal'],
    expReward: 25,
    goldReward: { min: 15, max: 25 }
  },
  desert_scorpion: {
    id: 'desert_scorpion',
    name: '沙漠巨蝎',
    icon: '🦂',
    realm: '筑基',
    realmLevel: 3,
    baseStats: { maxHp: 100, attack: 28, defense: 12, speed: 95 },
    skills: ['poison_sting', 'pincer_attack'],
    drops: ['scorpion_tail'],
    expReward: 30,
    goldReward: { min: 18, max: 30 }
  },
  mummy_warrior: {
    id: 'mummy_warrior',
    name: '木乃伊战士',
    icon: '🧟',
    realm: '筑基',
    realmLevel: 5,
    baseStats: { maxHp: 180, attack: 32, defense: 15, speed: 70 },
    skills: ['wrap', 'ancient_curse'],
    drops: ['mummy_bandage', 'ancient_relic'],
    expReward: 45,
    goldReward: { min: 25, max: 40 }
  },
  ice_wolf: {
    id: 'ice_wolf',
    name: '冰狼',
    icon: '🐺',
    realm: '筑基',
    realmLevel: 5,
    baseStats: { maxHp: 150, attack: 30, defense: 10, speed: 110 },
    skills: ['frost_bite', 'howling_blizzard'],
    drops: ['wolf_pelt', 'ice_crystal'],
    expReward: 40,
    goldReward: { min: 22, max: 35 }
  },
  frost_giant: {
    id: 'frost_giant',
    name: '霜巨人',
    icon: '🧊',
    realm: '筑基',
    realmLevel: 7,
    baseStats: { maxHp: 250, attack: 40, defense: 20, speed: 60 },
    skills: ['ice_crush', 'frozen_armor'],
    drops: ['frost_essence'],
    expReward: 60,
    goldReward: { min: 35, max: 50 }
  },
  snow_demon: {
    id: 'snow_demon',
    name: '雪魔',
    icon: '👹',
    realm: '金丹',
    realmLevel: 1,
    baseStats: { maxHp: 300, attack: 50, defense: 18, speed: 90 },
    skills: ['blizzard', 'ice_prison'],
    drops: ['frozen_heart'],
    expReward: 80,
    goldReward: { min: 50, max: 70 }
  },
  void_walker: {
    id: 'void_walker',
    name: '虚空行者',
    icon: '👁️',
    realm: '金丹',
    realmLevel: 3,
    baseStats: { maxHp: 350, attack: 55, defense: 22, speed: 100 },
    skills: ['void_strike', 'phase_shift'],
    drops: ['void_essence'],
    expReward: 100,
    goldReward: { min: 60, max: 90 }
  },
  demon_lord: {
    id: 'demon_lord',
    name: '恶魔领主',
    icon: '👿',
    realm: '金丹',
    realmLevel: 5,
    baseStats: { maxHp: 500, attack: 70, defense: 30, speed: 85 },
    skills: ['hellfire', ],
    drops: ['demon_heart'],
    expReward: 150,
    goldReward: { min: 100, max: 150 }
  },
  abyss_dragon: {
    id: 'abyss_dragon',
    name: '深渊魔龙',
    icon: '🐉',
    realm: '元婴',
    realmLevel: 1,
    baseStats: { maxHp: 800, attack: 100, defense: 45, speed: 95 },
    skills: ['abyss_breath', 'dragon_roar', 'shadow_slash'],
    drops: ['dragon_scale', 'abyss_essence'],
    expReward: 300,
    goldReward: { min: 200, max: 300 }
  },
  fire_elemental: {
    id: 'fire_elemental',
    name: '火焰元素',
    icon: '🔥',
    realm: '金丹',
    realmLevel: 3,
    baseStats: { maxHp: 280, attack: 60, defense: 15, speed: 105 },
    skills: ['fireball', 'flame_burst'],
    drops: ['fire_essence'],
    expReward: 90,
    goldReward: { min: 55, max: 80 }
  },
  lava_golem: {
    id: 'lava_golem',
    name: '熔岩魔像',
    icon: '🗿',
    realm: '金丹',
    realmLevel: 5,
    baseStats: { maxHp: 400, attack: 55, defense: 35, speed: 65 },
    skills: ['lava_throw', 'molten_armor'],
    drops: ['lava_core'],
    expReward: 120,
    goldReward: { min: 70, max: 100 }
  },
  phoenix_chick: {
    id: 'phoenix_chick',
    name: '幼凤',
    icon: '🕊️',
    realm: '金丹',
    realmLevel: 7,
    baseStats: { maxHp: 350, attack: 75, defense: 20, speed: 120 },
    skills: ['phoenix_flame', 'rebirth'],
    drops: ['phoenix_feather'],
    expReward: 150,
    goldReward: { min: 90, max: 130 }
  },
  ancient_guardian: {
    id: 'ancient_guardian',
    name: '上古守卫',
    icon: '🗿',
    realm: '元婴',
    realmLevel: 2,
    baseStats: { maxHp: 600, attack: 80, defense: 40, speed: 75 },
    skills: ['stone_fist', 'ancient_seal'],
    drops: ['ancient_core'],
    expReward: 200,
    goldReward: { min: 120, max: 180 }
  },
  spirit_wraith: {
    id: 'spirit_wraith',
    name: '灵体幽魂',
    icon: '👻',
    realm: '元婴',
    realmLevel: 4,
    baseStats: { maxHp: 450, attack: 95, defense: 25, speed: 110 },
    skills: ['spirit_attack', 'soul_drain'],
    drops: ['spirit_essence'],
    expReward: 250,
    goldReward: { min: 150, max: 220 }
  },
  celestial_beast: {
    id: 'celestial_beast',
    name: '天界神兽',
    icon: '🦁',
    realm: '元婴',
    realmLevel: 6,
    baseStats: { maxHp: 700, attack: 110, defense: 35, speed: 90 },
    skills: ['divine_roar', 'celestial_strike'],
    drops: ['celestial_gem'],
    expReward: 350,
    goldReward: { min: 200, max: 300 }
  },
  chaos_serpent: {
    id: 'chaos_serpent',
    name: '混沌巨蛇',
    icon: '🐍',
    realm: '元婴',
    realmLevel: 8,
    baseStats: { maxHp: 900, attack: 120, defense: 50, speed: 100 },
    skills: ['chaos_bite', 'void_poison'],
    drops: ['chaos_venom'],
    expReward: 400,
    goldReward: { min: 250, max: 350 }
  }
}
